---
name: CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tastybamboo/panda-ci:ruby-${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.3.7, 3.4.5]
        rails: [7.1, 7.2, 8.0]
    env:
      BUNDLE_PATH: vendor/bundle
      RAILS_ENV: test
      DISPLAY: :99
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Cache gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: |
            ${{ runner.os }}-ruby-${{ matrix.ruby }}-rails-${{ matrix.rails }}-
            gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruby-${{ matrix.ruby }}-rails-${{ matrix.rails }}-gems-
            ${{ runner.os }}-ruby-${{ matrix.ruby }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:password@postgres:5432/test
          RAILS_ENV: test
        run: |
          # Skip tests if no specs exist yet
          if [ -d "spec" ] && [ "$(find spec -name '*_spec.rb' | wc -l)" -gt 0 ]; then
            bundle exec rspec
          else
            echo "No specs found, skipping tests"
          fi

  lint:
    name: Linters
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tastybamboo/panda-ci:ruby-3.4.5
    env:
      BUNDLE_PATH: vendor/bundle
    steps:
      - uses: actions/checkout@v4

      - name: Cache gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-lint-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-lint-
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run StandardRB
        run: bundle exec standardrb

      - name: Run ERB Lint
        run: |
          if [ -f ".erb-lint.yml" ]; then
            bundle exec erb_lint app/views --lint-all
          else
            echo "No .erb-lint.yml found, skipping ERB lint"
          fi

      - name: Run Brakeman
        run: bundle exec brakeman --quiet --skip-files app/javascript/

      - name: Run bundle-audit
        run: |
          bundle exec bundle-audit update
          bundle exec bundle-audit check

      - name: Run YAML lint
        run: yamllint -c .yamllint .
